@startuml
actor Usuario as U

participant Main
participant "NodeMatrix" as Matriz
participant "JobQueue\ncreados" as Creados
participant "JobQueue\nenCola" as EnCola
participant "JobQueue\nenEjecucion" as EnEjecucion
participant "JobQueue\nfinalizados" as Finalizados
participant "JobQueue\nfallidos" as Fallidos
participant "JobQueue\nvalidados" as Validados

participant Scheduler
participant PreExecutionCheck as PreCheck
participant WorkerExecution as Worker
participant PostProcessing as Post

U -> Main : main()

activate Main

Main -> Creados : crear Jobs
Main -> Matriz : inicializar nodos

Main -> Scheduler : new Scheduler(...)
Main -> PreCheck : new PreExecutionCheck(...)
Main -> Worker : new WorkerExecution(...)
Main -> Post : new PostProcessing(...)

Main -> Main : Crear hilos y start()

deactivate Main

par Procesamiento concurrente

    group Scheduler (Ingreso de Jobs)
        loop Mientras haya jobs creados
            Scheduler -> Creados : popJob()

            Scheduler -> Matriz : ocuparNodo()
            activate Matriz
            critical "Sección crítica nodos"
                Matriz -> Matriz : asignar nodo
            end
            deactivate Matriz

            Scheduler -> EnCola : pushJob(job)
        end
    end group

    group Validación (PreExecutionCheck)
        loop Mientras haya jobs en cola
            PreCheck -> EnCola : popJob()

            alt Job inválido (15%)
                PreCheck -> Matriz : sacarDeServicio()
                activate Matriz
                critical "Sección crítica nodos"
                    Matriz -> Matriz : marcar fuera de servicio
                end
                deactivate Matriz

                PreCheck -> Fallidos : pushJob()
            else Job válido (85%)
                PreCheck -> Matriz : liberarNodo()
                activate Matriz
                critical "Sección crítica nodos"
                    Matriz -> Matriz : liberar nodo
                end
                deactivate Matriz

                PreCheck -> EnEjecucion : pushJob()
            end
        end
    end group

    group Ejecución (WorkerExecution)
        loop Mientras haya jobs en ejecución
            Worker -> EnEjecucion : popJob()

            alt Error (10%)
                Worker -> Fallidos : pushJob()
            else Éxito (90%)
                Worker -> Finalizados : pushJob()
            end
        end
    end group

    group Verificación final (PostProcessing)
        loop Mientras haya jobs finalizados
            Post -> Finalizados : popJob()

            alt Inconsistente (5%)
                Post -> Fallidos : pushJob()
            else Correcto (95%)
                Post -> Validados : pushJob()
            end
        end
    end group

end par

Main -> Validados : obtener resultados
Main -> Fallidos : obtener resultados

@enduml